### PR TITLE
Remove groups stuff

### PR DESCRIPTION
**Pull request by KK4OXJ**
Removed a bunch of stuff about groups.

### CODE REVIEW

**Comment by lpolepeddi** [comment]
Thanks @KK4OXJ, +1. Need two more.

**Comment by KK4OXJ** [comment]
@lpolepeddi two more what? Did I miss some groups stuff?

**Comment by lpolepeddi** [comment]
@KK4OXJ My bad, I should have clarified - we now need two more +1s. As per our [peer review process](https://github.com/RyzacInc/help.codecademy.com/wiki/How-to-contribute-to-this-repo%3F#peer-review), we wait for three +1s before merging a PR.

**Comment by KK4OXJ** [comment]
@lpolepeddi Oh, I see. 

Since groups are gone, what should users do when they find "anything missing or unclear" in [this file](https://github.com/RyzacInc/help.codecademy.com/blob/master/published/general/where-can-i-find-a-reference-for-a-programming-languages-syntax.md)? I'm guessing they should email CC?

**Comment by lpolepeddi** [comment]
@KK4OXJ Let's remove this line for now:

> If you ever find anything missing or unclear, the moderators look after this part of the site and would be happy to improve the content. You can bring your suggestions to their attention by starting a discussion in this group.

When we come up with a better replacement for discussions on the site, we'll add it back in.

**Comment by KK4OXJ** [comment]
@lpolepeddi OK, I removed that paragraph.  
I'm still learning how to use GitHub, is there a way to add the modified file to this pull request, or do I need to create a new PR?

**Comment by lpolepeddi** [comment]
@KK4OXJ Now that you've modified the file, do
1. `git add .`
2. `git commit -m "your message here"`
3. `git push origin master`
as you would with other commits. By committing to your repo's master branch, this pull request will update with that commit.

**Comment by KK4OXJ** [comment]
@lpolepeddi Should have seen that, it's right above the comment box here, but thanks for the help :smile:

I committed the wrong thing the second time, when I was actually removing the .c9 folder from the commit.

**Comment by AlbionsRefuge** [comment]
+1  

Thanks for digging those out Zeke.

**Comment by GaurangTandon** [comment]
+1 great work!

>

**Comment by lpolepeddi** [comment]
Thanks @KK4OXJ and peer reviewers. The articles have been updated. 

I made two small changes [here](https://github.com/RyzacInc/help.codecademy.com/commit/bb985d86609f8ef570335e203b20935b8d11ff96) and [here](https://github.com/RyzacInc/help.codecademy.com/commit/8895b97a6ea3d2283416e312478400c2e55e317a) as we don't want users using this form at this time.

**Pull request merged**
